### ISSUE TITLE
Calendar initialization

### ISSUE THREAD

**Issue by StefanVam** [lilcodelab/Xamarin.Plugin.Calendar#20]
Hi,I have some questions,when i open a page which has the Calendar
1. Calendar seems to load twice first time
2. It also seems to load twice when swipe to cross year

Is these something wrong i used ,below is my sample code:
```          
var calendar = new Xamarin.Plugin.Calendar.Controls.Calendar() {
               VerticalOptions = LayoutOptions.FillAndExpand, HorizontalOptions = 
               LayoutOptions.FillAndExpand 
            };
this.Content = new StackLayout { Children = { calendar } };
```

**Comment by PenguinPero** [comment]
Both might be the same issue
Second one we are aware of, it is because 2 properties change at the same time and both are queuing animation on the calendar
This was not an issue on previous versions, but one bugfix where we removed Year/Month hash check caused it

We will see when me or @jsabic  can fix this

**Comment by StefanVam** [comment]
@PenguinPero Thanks for your reply,I expect  it is fixed in the near future.

**Comment by antonioseric** [comment]
this is fixed. it will be available in next version.
